### ISSUE TITLE
Found the problem

### ISSUE THREAD

**Issue by MethHeadAlert** [CyanogenMod/android_device_htc_hima-common#5]
Commits on Oct 29, 2015
@intervigilium
hima: Clean up vendor scripts …
intervigilium committed on Oct 27
848ab1e

@intervigilium
hima: Clean up proprietary library listing …
intervigilium committed on Oct 27
f996441

hima: Clean up system properties …
intervigilium committed on Oct 27
255a529  

These three commits deleted functions ie Double Tap Functions, IR Blaster, and the reason Bluetooth had to be renamed. Please revert and keep files alone. The second part is found in TheMuppets

**Comment by chadouming** [comment]
you need to make comment on the gerrit, or reach directly to the devs. They won't look here, nor will they accept pull request directly from github.
